#!/bin/bash

set -e

CURRENT_DIR=$(cd $(dirname $0) ; pwd)
SCRIPTS=(
    setup-homebrew
)

for SCRIPT in "${SCRIPTS[@]}" ; do
    echo "$SCRIPT"
    "$CURRENT_DIR/$SCRIPT" 2>&1 | sed 's/^/  /'
done

echo "Installing zsh + oh-my-zsh"
if [ -z "$(which zsh)" ] ; then
  pkg install zsh starship | sed 's/^/  /'
fi
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" | sed 's/^/  /'

echo "Installing symlinks"
"$CURRENT_DIR/install-symlink" "$CURRENT_DIR/inputrc" "$HOME/.inputrc" | sed 's/^/  /'
"$CURRENT_DIR/install-symlink" "$CURRENT_DIR/profile" "$HOME/.profile" | sed 's/^/  /'
"$CURRENT_DIR/install-symlink" "$CURRENT_DIR/zshrc" "$HOME/.zshrc" | sed 's/^/  /'
"$CURRENT_DIR/install-symlink" "$CURRENT_DIR/gitconfig" "$HOME/.gitconfig" | sed 's/^/  /'
"$CURRENT_DIR/install-symlink" "$CURRENT_DIR/atuin" "$HOME/.config/atuin/config.toml"

echo "Done."

echo ""
echo "Login again to use your new shell profile"
