#!/bin/bash

set -e

echo "Setting identity"
git config --global user.name "Chetan Padia"
git config --global user.email "chetbox@users.noreply.github.com"

echo "Setting aliases"
git config --global alias.co "checkout"
git config --global alias.d "diff"
git config --global alias.dc "diff --cached"
git config --global alias.s "status --short --branch"
